- # storyboarding
  name: "storyboarding"
  color: "f4ccff"
  description: "To be applied for storyboarding related issues"
- # pedagogy
  name: "pedagogy"
  color: "8641c1"
  description: "To be applied for pedagogy related issues"
- # bug
  name: "bug"
  color: "b60205"
  description: "This is bug"
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: "To be applied for invalid issues"
- # Approved
  name: ":heavy_check_mark: approved"
  color: "e6e6e6"
  description: "To be applied for approved issues"
- # Request for review
  name: "request for review"
  color: "e6e6e6"
  description: "To be applied for issues which are requested for reviewing"
  
  
  
  
## For refernce or adding more labels https://github.com/crazy-max/ghaction-github-labeler
