name: labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3
    # The following job will delete the script that creates dev and testing branches 
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "admin@vlabs.ac.in"
          git config --local user.name "vleadadmin"
          git checkout main
          git rm -rf .github/workflows/labels.yml
          git commit -m "Label script is deleted."
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
          force: true
          branch: main
